version: "3.9"
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  backend:
    build: .
    container_name: mws-ecommerce-backend
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/mws-ecommerce
      RABBITMQ_URI: amqp://rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq
volumes:
  mongo_data: